"""Tools for the ETL Agent"""

import os

import pandas as pd
import requests


class ETLTools:
    def __init__(self):
        pass

    def extract_load(self, urls: list, output_folder: str, format: str):
        """Tool to extract data from a URL and loads it to a specified folder in the desired format.

        Args:
            urls (list): A list of URLs to extract data from.
            output_folder (str): The folder where the extracted data will be saved.
            format (str): The format in which to save the data. Supported formats are 'csv', 'json', and 'parquet'.

        Returns:
            str: The path to the saved file.
        """
        data = []
        try:
            # Extract data from each URL
            for url in urls:
                response = requests.get(url)
                response.raise_for_status()  # Raise an error for bad responses
                data.append(response.json())

            # Convert the response content to a DataFrame
            data = pd.DataFrame([item["results"] for item in data])

            # Ensure the output folder exists
            os.makedirs(output_folder, exist_ok=True)

            # Determine the output file path based on the desired format
            if format == "csv":
                output_file = os.path.join(output_folder, "data.csv")
                data.to_csv(output_file, index=False)
            elif format == "json":
                output_file = os.path.join(output_folder, "data.json")
                data.to_json(output_file, orient="records", lines=True)
            elif format == "parquet":
                output_file = os.path.join(output_folder, "data.parquet")
                data.to_parquet(output_file, index=False)
            else:
                raise ValueError("Unsupported format. Please choose 'csv', 'json', or 'parquet'.")

            return f"Data successfully extracted and saved to {output_file}"

        except requests.exceptions.RequestException as e:
            return f"Failed to extract data from URLs: {e}"

    # This function will not directly transforms the datga, but it will generate the context of the data,
    # which will help LLM to generate the code for transformation.
    def transform_load_context(self, file_path: str):
        """Tool to generate the context of the data from a file.
        Args:
            file_path (str): The path to the file to generate context from.
        Returns:
            str: The context of the data.
        """

        # Step 1: Read the data
        file_extension = os.path.splitext(file_path)[1]
        if file_extension == ".csv":
            data = pd.read_csv(file_path)
        elif file_extension == ".json":
            data = pd.read_json(file_path)
        elif file_extension == ".parquet":
            data = pd.read_parquet(file_path)
        else:
            raise ValueError(
                "Unsupported file format. Please provide a CSV, JSON, or Parquet file."
            )

        # Step 2: Generate the context of the data
        context = str(data.head(3))  # Top 3 records for the context
        return context

    # Here we will execute the code generated by the LLM, but we will not be able to see the
    # result of the code, but we can see if the code is executed successfully or not.
    def execute_code(self, code: str):
        """Executes the provided code string in a local scope.

        Args:
            code (str): The code to execute.
        Returns:
            Str: The result of the executed code, if any.
        """

        try:
            exec(code)
            return "Code executed successfully!"
        except Exception as e:
            return f"Failed to execute code: {e}"


if __name__ == "__main__":
    etl_tools = ETLTools()

    # testing the extract_load function
    # urls = ["https://pokeapi.co/api/v2/pokemon/"]
    # output_folder = "data"
    # format = "csv"
    # etl_tools.extract_load(urls, output_folder, format)

    # testing the transform_load_context function
    file_path = "data/data.csv"
    context = etl_tools.transform_load_context(file_path)
    print(context)
