from operator import add
from typing import Annotated, Literal

from pydantic import BaseModel, Field


class AgentSchema(BaseModel):
    """Tracking the state of the agent.
    This class contains everything that a agent will have."""

    # I know that my variable is of list type, but  Annotated will tell me how this variable will behave
    # See below, I know that "messages" is a list, but how should the list behave?
    # It should behave like a basket where we are keep on adding the data and nothing else (not updating, not removing etc).
    messages: Annotated[list, add] = Field(
        ..., description="List of messages to be processed by the agent."
    )  # Chat history
    user_question = str = Field(..., description="The original question asked by the user.")
    curated_ques: str = Field(..., description="Curated user question.")
    prompt_query: str = Field(
        ...,
        description="A detailed prompt with SQL DB context that will help agent to generate SQL query.",
    )  # Here context can be fetched from Vector Database / PGVector

    # Here, I can use JEV / GUARDRAILS
    is_safe: Literal["Yes", "No"] = Field(
        ..., description="Indicates whether the generated SQL query is safe or not?"
    )
    generated_sql_query: str = Field(
        ...,
        description="The SQL Query generated by the agent based on the curated question and prompt context.",
    )
    sql_query_execution_result: str = Field(
        ..., description="The result of executing the generated SQL query on the database"
    )
    final_answer: str = Field(
        ...,
        description="The final answer generated by the agent based on the generated SQL query on the database",
    )


class JudgeSchema(BaseModel):
    """LLM-as-a-Judge Schema
    Tells whether a query is safe to run or not"""

    answer: Literal["Yes", "No"] = Field(
        ..., description="Indicates whether the generated SQL query is safe to execute or not"
    )
    comments: str = Field(
        ..., description="Additional comments or feedback from the judge regarding the SQL query"
    )
